name: Cypress acceptance tests
description: "Run the Cypress acceptance tests for a Renku deployment"
inputs:
  e2e-folder:
    description: "The folder containing the Cypress tests"
    required: false
    default: "cypress/e2e/"
  e2e-infrastructure-check:
    description: "The Cypress test to check the infrastructure"
    required: false
    default: "verifyInfrastructure"
  e2e-suffix:
    description: "The suffix of the Cypress tests"
    required: false
    default: ".cy.ts"
  e2e-target:
    description: "The target spec to execute"
    required: true
  renku-path:
    description: "The path to the Renku repository."
    required: false
    default: "renku"
  renku-reference:
    description: "The reference (e.g., branch/commit/tag) on the Renku repository to check out."
    required: false
    default: "master"
  renku-release:
    description: "The name of the Renku helm release."
    required: true
  renku-repository:
    description: "The name of the Renku repository."
    required: false
    default: "SwissDataScienceCenter/renku"
  settings-browser:
    description: "The browser to use for the Cypress tests"
    required: false
    default: "chrome"
  settings-working-directory:
    description: "The working directory for the Cypress tests"
    required: false
    default: "renku/cypress-tests"
  test-user-email:
    description: "The email address of the test user"
    required: false
    default: "renku@datascience.ch"
  test-user-firstname:
    description: "The first name of the test user"
    required: false
    default: "Renku"
  test-user-lastname:
    description: "The last name of the test user"
    required: false
    default: "Bot"
  test-user-password:
    description: "The password of the test user"
    required: true
  test-user-username:
    description: "The username of the test user"
    required: false
    default: "renku-test"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      name: "Checkout the Renku repository"
      with:
        repository: ${{ inputs.renku-repository }}
        path: ${{ inputs.renku-path }}
        ref: ${{ inputs.renku-reference }}

    - uses: actions/setup-node@v4
      name: Setup Node v22
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: ${{ inputs.settings-working-directory }}

    - uses: cypress-io/github-action@v6
      name: "Verify infrastructure and run the target Cypress test"
      id: cypress-acceptance-tests
      env:
        BASE_URL: https://${{ inputs.renku-release }}.dev.renku.ch
        TEST_EMAIL: ${{ inputs.test-user-email }}
        TEST_FIRST_NAME: ${{ inputs.test-user-firstname }}
        TEST_LAST_NAME: ${{ inputs.test-user-lastname }}
        TEST_PASSWORD: ${{ inputs.test-user-password }}
        TEST_USERNAME: ${{ inputs.test-user-username }}
      with:
        browser: ${{ inputs.settings-browser }}
        spec: |
          ${{ inputs.e2e-folder }}${{ inputs.e2e-infrastructure-check }}${{ inputs.e2e-suffix }}
          ${{ inputs.e2e-folder }}${{ inputs.e2e-target }}${{ inputs.e2e-suffix }}
        working-directory: ${{ inputs.settings-working-directory }}

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Cypress screenshot - ${{ inputs.e2e-target }}
        path: ${{ inputs.settings-working-directory }}/cypress/screenshots
        retention-days: 7

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Cypress video - ${{ inputs.e2e-target }}
        path: ${{ inputs.settings-working-directory }}/cypress/videos
        retention-days: 3
