name: "test-renku"
description: "Run the legacy Scala/Selenium acceptance tests for a Renku CI deployment"
inputs:
  kubeconfig:
    description: "The path to a kubeconfig file to be used for helm/kubectl commands."
    required: true
  renku-release:
    description: "The name of the helm release."
    required: true
  s3-results-host:
    default: os.zhdk.cloud.switch.ch
    description: S3 host where the tests artifacts have been stored
    required: true
  s3-results-bucket:
    default: dev-acceptance-tests-results
    description: Name of the S3 bucket where the tests artifacts have been stored
    required: true
  s3-results-access-key:
    description: Access key to the S3 bucket where the tests artifacts have been stored
    required: true
  s3-results-secret-key:
    description: Secret key to the S3 bucket where the tests artifacts have been stored
    required: true
  test-timeout-mins:
    description: "The timeout in mins to wait for the helm tests to complete."
    required: false
    default: "60"
runs:
  using: "composite"
  steps:
    - name: "Setup Helm"
      uses: azure/setup-helm@v1
      with:
        version: "3.6.3"
    - name: "Run tests"
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        KUBECONFIG: ${{ inputs.kubeconfig }}
        RENKU_RELEASE: ${{ inputs.renku-release }}
        TEST_TIMEOUT_MINS: ${{ inputs.test-timeout-mins }}
    - name: Download artifact for packaging on failure
      if: failure()
      uses: SwissDataScienceCenter/renku-actions/download-test-artifacts@v1.21.0
      with:
        s3-results-host: ${{ inputs.s3-results-host }}
        s3-results-bucket: ${{ inputs.s3-results-bucket }}
        s3-results-access-key: ${{ inputs.s3-results-access-key }}
        s3-results-secret-key: ${{ inputs.s3-results-secret-key }}
        s3-results-artifacts-path: "tests-artifacts-${{ github.sha }}"
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v6
      with:
        name: acceptance-test-artifacts
        path: ${{ github.workspace }}/test-artifacts/
