name: Update renku actions

on:
  release:
    types: [published]

jobs:
  update-renku-actions:
    strategy:
      matrix:
        repo:
          - name: SwissDataScienceCenter/renku
            ref: master
          - name: SwissDataScienceCenter/renku-notebooks
            ref: master
          - name: SwissDataScienceCenter/renku-ui
            ref: main
          - name: SwissDataScienceCenter/renku-gateway
            ref: master
          - name: SwissDataScienceCenter/renku-graph
            ref: development
    runs-on: ubuntu-latest
    steps:
      - name: Get release tag
        run: echo "NEW_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout repo to be updated
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo.name }}
          ref: ${{ matrix.repo.ref }}
          fetch-depth: 1
      - name: Checkout renku-actions repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: .actions-repo
      - name: Update actions version
        uses: ./.actions-repo/update-renku-actions
      - name: Remove renku-actions repo
        run: rm -rf ./.actions-repo
      - name: Submit PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
          commit-message: "chore(ci): Update renku actions to ${{ env.NEW_VERSION }}"
          title: "chore(ci): Update renku actions to ${{ env.NEW_VERSION }}"
          branch: "chore-update-renku-action-${{ env.NEW_VERSION }}"
          delete-branch: true
          author: "Renku Bot <renku@datascience.ch>"
          committer: "Renku Bot <renku@datascience.ch>"
